export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const TWITTER_GET_SUCCESS = 'TWITTER_GET_SUCCESS';

export const TOGGLE_SUCCESS = 'TOGGLE_SUCCESS';

export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
